name: model-based-testing-data-structures
root: <%= Dir.pwd %>

windows:
  - frontend:
      layout: main-vertical
      panes:
        - vim
        - npm run dev
        - npm run test:watch
        -
